export const CORAL_GECKO_PRESENTATION = {
  baselineId: 'coral-gecko-master-v1',
  displayScale: 1.25,
  animation: {
    idlePlaybackRate: 1,
    runPlaybackRate: 3.2,
    turnPlaybackRate: 1.2,
    crossfadeSeconds: 0.16,
    footstepEventsPerSecond: 6.4,
    turnTriggerRadians: 0.45,
    turnHoldSeconds: 0.38,
  },
  combat: {
    profileId: 'coral-gecko-combat-master-v1',
    system: 'basic-attack',
    skillsEnabled: false,
    targeting: {
      mode: 'nearest-live-target',
      turnSpeedRadiansPerSecond: 12,
      contactToleranceDegrees: 8,
    },
    demoTarget: {
      name: '甲壳训练虫',
      maxHealth: 84,
      respawnSeconds: 1.8,
      spawnDistance: 2.55,
    },
    hitFeedback: {
      biteDamage: 16,
      pounceDamage: 18,
      clawDamage: 12,
      tailSwipeDamage: 14,
      biteRange: 2.55,
      pounceRange: 2.95,
      clawRange: 2.75,
      tailSwipeRange: 3.1,
      flashSeconds: 0.1,
      cameraTrauma: 0.34,
      knockbackSpeed: 2.3,
      particleCount: 9,
    },
    primaryCombo: ['Bite', 'Pounce', 'TailSwipe'],
    attackNames: { Bite: '快速撕咬', Pounce: '跃起重咬', TailSwipe: '尾扫' },
    comboResetSeconds: 1.15,
    biteDurationSeconds: 0.6,
    biteContactSeconds: 0.3,
    pounceDurationSeconds: 0.9,
    pounceContactSeconds: 0.43,
    leapBiteMotion: {
      clipName: 'Bite',
      clipPlaybackRate: 0.78,
      crouchEndProgress: 0.22,
      contactProgress: 0.478,
      landingProgress: 0.68,
      visualTravel: 0.78,
      maximumLift: 0.3,
      crouchDepth: 0.1,
      landingDepth: 0.11,
      landingCameraTrauma: 0.2,
    },
    clawDurationSeconds: 0.73,
    clawContactSeconds: 0.3,
    tailSwipeDurationSeconds: 0.87,
    tailSwipeContactSeconds: 0.4,
    hitDurationSeconds: 0.47,
    deathDurationSeconds: 1.2,
    oneShotCrossfadeSeconds: 0.08,
  },
  contactShadow: {
    bodyOpacity: 0.24,
    headOpacity: 0.18,
    tailOpacity: 0.12,
    bodyWidth: 1.18,
    bodyLength: 0.62,
    headWidth: 0.58,
    headLength: 0.44,
    tailWidth: 0.92,
    tailLength: 0.25,
    groundLift: 0.045,
  },
  weight: {
    accelerationDamping: 18,
    decelerationDamping: 11,
    turnFollowDamping: 7,
    stepImpactDecay: 13,
    stopSettleSeconds: 0.22,
    stopSettleDepth: 0.022,
    runLift: 0.006,
    stepCompression: 0.018,
    widthCompensation: 0.28,
    turnLean: 0.052,
    headFollow: 0.045,
    tailCounterbalance: 0.04,
    tailCounterbalanceStep: 0.012,
    shadowBaseOpacity: 0.28,
    shadowImpactOpacity: 0.1,
    shadowSettleOpacity: 0.04,
    shadowImpactContraction: 0.055,
    groundCorrectionDamping: 24,
    maximumGroundCorrection: 0.48,
  },
  material: {
    minimumRoughness: 0.52,
    maximumRoughness: 0.88,
    maximumMetalness: 0.04,
    normalStrength: 1.18,
    aoStrength: 1.28,
    environmentIntensity: 0.72,
    maximumAnisotropy: 8,
  },
  dust: {
    poolSize: 14,
    durationSeconds: 0.58,
    backOffset: 0.48,
    lateralOffset: 0.34,
    groundLift: 0.18,
    startScale: 0.42,
    scaleVariance: 0.08,
    backwardVelocity: 0.08,
    lateralVelocity: 0.035,
    liftVelocity: 0.11,
    liftVelocityVariance: 0.035,
    expansionPerSecond: 1.9,
    peakOpacity: 0.62,
    materialColor: 0xffd59a,
    gradientCenter: 'rgba(255, 233, 194, 1)',
    gradientMiddle: 'rgba(216, 176, 119, .82)',
    gradientEdge: 'rgba(92, 77, 58, 0)',
    renderOrder: 10,
  },
  validation: {
    maximumPlantedFootError: 0.16,
    targetRunningDustPuffs: { minimum: 4, maximum: 8 },
    desktopViewport: { width: 1440, height: 900 },
    mobileLandscapeViewport: { width: 844, height: 390 },
  },
} as const

export type CoralGeckoPresentation = typeof CORAL_GECKO_PRESENTATION
