export const CORAL_GECKO_PRESENTATION = {
  baselineId: 'coral-gecko-master-v1',
  displayScale: 1.25,
  animation: {
    idlePlaybackRate: 1,
    runPlaybackRate: 3.2,
    turnPlaybackRate: 1.2,
    crossfadeSeconds: 0.16,
    footstepEventsPerSecond: 6.4,
    turnTriggerRadians: 0.45,
    turnHoldSeconds: 0.38,
  },
  weight: {
    accelerationDamping: 18,
    decelerationDamping: 11,
    turnFollowDamping: 7,
    stepImpactDecay: 13,
    stopSettleSeconds: 0.22,
    stopSettleDepth: 0.022,
    runLift: 0.006,
    stepCompression: 0.018,
    widthCompensation: 0.28,
    turnLean: 0.052,
    headFollow: 0.045,
    tailCounterbalance: 0.04,
    tailCounterbalanceStep: 0.012,
    shadowBaseOpacity: 0.28,
    shadowImpactOpacity: 0.1,
    shadowSettleOpacity: 0.04,
    shadowImpactContraction: 0.055,
    groundCorrectionDamping: 24,
    maximumGroundCorrection: 0.48,
  },
  material: {
    minimumRoughness: 0.52,
    maximumRoughness: 0.88,
    maximumMetalness: 0.04,
    normalStrength: 1.18,
    aoStrength: 1.28,
    environmentIntensity: 0.72,
    maximumAnisotropy: 8,
  },
  dust: {
    poolSize: 14,
    durationSeconds: 0.58,
    backOffset: 0.48,
    lateralOffset: 0.34,
    groundLift: 0.18,
    startScale: 0.42,
    scaleVariance: 0.08,
    backwardVelocity: 0.08,
    lateralVelocity: 0.035,
    liftVelocity: 0.11,
    liftVelocityVariance: 0.035,
    expansionPerSecond: 1.9,
    peakOpacity: 0.62,
    materialColor: 0xffd59a,
    gradientCenter: 'rgba(255, 233, 194, 1)',
    gradientMiddle: 'rgba(216, 176, 119, .82)',
    gradientEdge: 'rgba(92, 77, 58, 0)',
    renderOrder: 10,
  },
  validation: {
    maximumPlantedFootError: 0.16,
    targetRunningDustPuffs: { minimum: 4, maximum: 8 },
    desktopViewport: { width: 1440, height: 900 },
    mobileLandscapeViewport: { width: 844, height: 390 },
  },
} as const

export type CoralGeckoPresentation = typeof CORAL_GECKO_PRESENTATION
