import { SCARLET_GECKO_PRESENTATION } from './scarlet-gecko-character-presentation'

export const SCARLET_HUNTER_PRESENTATION = {
  baselineId: 'scarlet-hunter-quadruped-template-v1',
  displayScale: 196,
  stageGrowthRatio: 1.18,
  templateId: 'meshy-quadruped-combat-v1',
  animation: {
    idlePlaybackRate: 0.9,
    runPlaybackRate: 1.15,
    turnPlaybackRate: 1,
    crossfadeSeconds: 0.13,
    footstepEventsPerSecond: 4.2,
  },
  combat: {
    ...SCARLET_GECKO_PRESENTATION.combat,
    profileId: 'scarlet-hunter-combat-master-v1',
    system: 'basic-attack',
    skillsEnabled: false,
    primaryCombo: ['Claw', 'Pounce', 'TailSwipe'],
    comboResetSeconds: 1.28,
    pounceDurationSeconds: 0.82,
    pounceContactSeconds: 0.42,
    clawDurationSeconds: 0.62,
    clawContactSeconds: 0.22,
    tailSwipeDurationSeconds: 1.10,
    tailSwipeContactSeconds: 0.56,
    attackPlaybackRate: { Pounce: 1.16, Claw: 1.18, TailSwipe: 1.20 },
    attackNames: { Pounce: '双爪跃扑', Claw: '裂爪', TailSwipe: '旋身尾扫' },
    pounceMotion: {
      anticipationSeconds: 0.18,
      launchSeconds: 0.22,
      contactSeconds: 0.42,
      visualTravel: 0.72,
      damageEvents: 1,
    },
    hitFeedback: {
      ...SCARLET_GECKO_PRESENTATION.combat.hitFeedback,
      pounceDamage: 20,
      clawDamage: 14,
      tailSwipeDamage: 18,
      pounceRange: 3.15,
      clawRange: 2.96,
      tailSwipeRange: 3.28,
      cameraTrauma: 0.42,
      knockbackSpeed: 2.8,
      particleCount: 12,
    },
  },
  asset: {
    triangles: 54_828,
    bones: 27,
    clips: ['Idle', 'Walk', 'Run', 'Turn', 'Claw', 'Pounce', 'TailSwipe', 'Hit', 'Death'],
    sourceModel: 'scarlet-hunter-meshy-rigged-walking-v4.glb',
    runtimeModel: 'scarlet-hunter-quadruped-v1.glb',
    bodyPlan: 'broad-chested-hunter-drake',
    artStyle: 'stylized-handpainted-quadruped',
  },
  silhouette: {
    lengthRatio: 1.31,
    widthRatio: 1.08,
    heightRatio: 1.16,
    dominantRead: 'crested-scarlet-pounce-drake',
  },
  material: {
    minimumRoughness: 0.72,
    maximumRoughness: 0.9,
    maximumMetalness: 0,
    normalStrength: 0,
    aoStrength: 0.82,
    environmentIntensity: 0.58,
    maximumAnisotropy: 8,
  },
} as const

export type ScarletHunterPresentation = typeof SCARLET_HUNTER_PRESENTATION
